export const suggestArray = [
    "Compartilhe sua jornada e inspire outros a seguir o mesmo caminho.",
    "Suas palavras têm o poder de criar impacto. O que você quer compartilhar hoje?",
    "Cada história é única. Conte a sua e inspire o mundo ao seu redor.",
    "Seja a inspiração que você procura. Compartilhe suas conquistas e desafios.",
    "Hoje é o dia perfeito para compartilhar algo que possa motivar alguém.",
    "Não subestime o poder de suas palavras. Elas podem tocar corações e mudar vidas.",
    "Sua voz é única. Faça-a ser ouvida e inspire positivamente.",
    "Compartilhe suas realizações e celebre cada passo na sua jornada.",
    "Inspire outros com sua coragem e determinação.",
    "O mundo precisa ouvir sua história. Não tenha medo de compartilhá-la.",
    "Crie conexões através das suas palavras. Você nunca sabe quem pode ser impactado.",
    "Cada postagem é uma oportunidade de espalhar positividade e inspiração.",
    "Você tem o poder de influenciar positivamente. O que você escolhe compartilhar hoje?",
    "Seu ponto de vista é valioso. Compartilhe e enriqueça a perspectiva dos outros.",
    "Crie um impacto positivo compartilhando o que te inspira diariamente.",
    "Celebre as pequenas vitórias e inspire outros a fazerem o mesmo.",
    "A autenticidade atrai. Seja genuíno em suas postagens e inspire confiança.",
    "Cada postagem é uma oportunidade de espalhar luz. Ilumine o dia de alguém hoje!",
    "Transforme suas experiências em lições e compartilhe sabedoria com o mundo.",
    "A jornada é tão importante quanto o destino. Compartilhe cada passo do seu caminho.",
    "A inspiração está em todo lugar. O que te inspira hoje?",
    "Seja a razão pela qual alguém acredita no poder da mudança.",
    "Compartilhe suas ideias e veja o impacto positivo que elas podem ter.",
    "Sua voz é uma ferramenta poderosa. Use-a para inspirar, motivar e educar.",
    "A beleza está nas histórias que contamos. Compartilhe a sua e inspire outros.",
    "Cada postagem é uma oportunidade de criar conexões significativas. O que você vai compartilhar hoje?",
    "A inspiração começa com uma mensagem. Que mensagem você quer enviar hoje?",
    "Suas palavras têm o poder de criar um efeito dominó de positividade. Comece a onda.",
    "Compartilhe sua paixão e inspire outros a perseguirem a deles.",
    "A vida é cheia de momentos dignos de serem compartilhados. O que você vai compartilhar hoje?"
  ]
